export class AppUserAuth {
    RoleName: string = '';
    isAuthenticated: boolean = false;
    canAddBrand: boolean = false;
    canEditBrand: boolean = false;
    canViewBrand: boolean = false;
    canDeleteBrand: boolean = false;
    canAddCategory: boolean = false;
    canEditCategory: boolean = false;
    canViewCategory: boolean = false;
    canDeleteCategory: boolean = false;
    canAddPrivateoffer: boolean = false;
    canEditPrivateoffer: boolean = false;
    canDeletePrivateoffer: boolean = false;
    canViewPrivateoffer: boolean = false;
    canAddProduct: boolean = false;
    canEditProduct: boolean = false;
    canDeleteProduct: boolean = false;
    canViewProduct: boolean = false;
    canAddCustomer: boolean = false;
    canEditCustomer: boolean = false;
    canDeleteCustomer: boolean = false;
    canViewCustomer: boolean = false;
}